# Generated by Django 3.2.7 on 2021-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
